[phases.setup]
nixPkgs = ['nodejs_22']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npx prisma generate', 'NEXTAUTH_URL=http://localhost:3000 NEXTAUTH_SECRET=dummy next build']

[start]
cmd = 'npm start'
